// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.2
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
lv_obj_t *ui_Screen1;
lv_obj_t *ui_DashboardPanel;
lv_obj_t *ui_ProbeGroup;
lv_obj_t *ui_Probe1Group;
lv_obj_t *ui_Probe1Temp;
void ui_event_Probe1Target( lv_event_t * e);
lv_obj_t *ui_Probe1Target;
lv_obj_t *ui_Probe1TempLabel;
lv_obj_t *ui_Probe1TargetLabel;
lv_obj_t *ui_Probe1Name;
lv_obj_t *ui_Probe2Group;
lv_obj_t *ui_Probe2Temp;
void ui_event_Probe2Target( lv_event_t * e);
lv_obj_t *ui_Probe2Target;
lv_obj_t *ui_Probe2TempLabel;
lv_obj_t *ui_Probe2TargetLabel;
lv_obj_t *ui_Probe2Name;
lv_obj_t *ui_Probe3Group;
lv_obj_t *ui_Probe3Temp;
void ui_event_Probe3Target( lv_event_t * e);
lv_obj_t *ui_Probe3Target;
lv_obj_t *ui_Probe3TempLabel;
lv_obj_t *ui_Probe3TargetLabel;
lv_obj_t *ui_Probe3Name;
lv_obj_t *ui_GrillPanel;
void ui_event_GrillTemp( lv_event_t * e);
lv_obj_t *ui_GrillTemp;
lv_obj_t *ui_GrillTempLabel;
lv_obj_t *ui_GrillTargetLabel;
lv_obj_t *ui_NavMenu;
lv_obj_t *ui_Smokeplus;
lv_obj_t *ui_SmokeplusLabel;
lv_obj_t *ui_SmokePlusSwitch;
lv_obj_t *ui_Mode;
lv_obj_t *ui_ModeLabel;
lv_obj_t *ui_ModeList;
lv_obj_t *ui_Pellets;
lv_obj_t *ui_PelletsLabel;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Image2;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Probe1Target( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_Probe1TargetLabel, target, "", "°");
      _ui_basic_set_property(ui_Probe1TargetLabel, _UI_BASIC_PROPERTY_POSITION_Y,  0);
}
}
void ui_event_Probe2Target( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_Probe2TargetLabel, target, "", "°");
      _ui_basic_set_property(ui_Probe2TargetLabel, _UI_BASIC_PROPERTY_POSITION_Y,  0);
}
}
void ui_event_Probe3Target( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_Probe3TargetLabel, target, "", "°");
      _ui_basic_set_property(ui_Probe3TargetLabel, _UI_BASIC_PROPERTY_POSITION_Y,  0);
}
}
void ui_event_GrillTemp( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_arc_set_text_value( ui_GrillTempLabel, target, "", "°");
}
}

///////////////////// SCREENS ////////////////////
void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_DashboardPanel = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_DashboardPanel, lv_pct(100));
lv_obj_set_height( ui_DashboardPanel, lv_pct(100));
lv_obj_set_x( ui_DashboardPanel, 0 );
lv_obj_set_y( ui_DashboardPanel, -1 );
lv_obj_set_align( ui_DashboardPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_DashboardPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_DashboardPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_DashboardPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DashboardPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ProbeGroup = lv_obj_create(ui_DashboardPanel);
lv_obj_set_width( ui_ProbeGroup, 291);
lv_obj_set_height( ui_ProbeGroup, 417);
lv_obj_set_x( ui_ProbeGroup, 15 );
lv_obj_set_y( ui_ProbeGroup, 15 );
lv_obj_set_align( ui_ProbeGroup, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_set_flex_flow(ui_ProbeGroup,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_ProbeGroup, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_BETWEEN);
lv_obj_clear_flag( ui_ProbeGroup, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_ProbeGroup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_ProbeGroup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_ProbeGroup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_ProbeGroup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Probe1Group = lv_obj_create(ui_ProbeGroup);
lv_obj_set_width( ui_Probe1Group, 90);
lv_obj_set_height( ui_Probe1Group, 427);
lv_obj_set_x( ui_Probe1Group, -1 );
lv_obj_set_y( ui_Probe1Group, 114 );
lv_obj_set_align( ui_Probe1Group, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_Probe1Group, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Probe1Group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Probe1Group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Probe1Group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Probe1Group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Probe1Temp = lv_bar_create(ui_Probe1Group);
lv_bar_set_range(ui_Probe1Temp, 32,230);
lv_bar_set_value(ui_Probe1Temp,180,LV_ANIM_OFF);
lv_obj_set_width( ui_Probe1Temp, 10);
lv_obj_set_height( ui_Probe1Temp, 375);
lv_obj_set_x( ui_Probe1Temp, 15 );
lv_obj_set_y( ui_Probe1Temp, 0 );
lv_obj_set_align( ui_Probe1Temp, LV_ALIGN_TOP_MID );
lv_obj_set_style_bg_color(ui_Probe1Temp, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Probe1Temp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Probe1Temp, lv_color_hex(0xFF0D0D), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Probe1Temp, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Probe1Temp, lv_color_hex(0xFFCD0B), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_Probe1Temp, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Probe1Temp, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Probe1Temp, LV_GRAD_DIR_VER, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Probe1Target = lv_slider_create(ui_Probe1Group);
lv_slider_set_range(ui_Probe1Target, 32,230);
lv_slider_set_value( ui_Probe1Target, 230, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_Probe1Target)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_Probe1Target, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Probe1Target, 16);
lv_obj_set_height( ui_Probe1Target, 382);
lv_obj_set_x( ui_Probe1Target, 15 );
lv_obj_set_y( ui_Probe1Target, -1 );
lv_obj_set_align( ui_Probe1Target, LV_ALIGN_TOP_MID );
lv_obj_set_style_bg_color(ui_Probe1Target, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Probe1Target, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Probe1Target, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Probe1Target, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Probe1Target, 30, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Probe1Target, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Probe1Target, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Probe1TempLabel = lv_label_create(ui_Probe1Group);
lv_obj_set_width( ui_Probe1TempLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Probe1TempLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Probe1TempLabel, -15 );
lv_obj_set_y( ui_Probe1TempLabel, 150 );
lv_label_set_text(ui_Probe1TempLabel,"190°");
lv_obj_set_style_text_color(ui_Probe1TempLabel, lv_color_hex(0xAB72C1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Probe1TempLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Probe1TempLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Probe1TargetLabel = lv_label_create(ui_Probe1Group);
lv_obj_set_width( ui_Probe1TargetLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Probe1TargetLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Probe1TargetLabel, -15 );
lv_obj_set_y( ui_Probe1TargetLabel, 0 );
lv_label_set_text(ui_Probe1TargetLabel,"185°");
lv_obj_set_style_text_font(ui_Probe1TargetLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Probe1Name = lv_label_create(ui_Probe1Group);
lv_obj_set_width( ui_Probe1Name, 57);
lv_obj_set_height( ui_Probe1Name, 19);
lv_obj_set_x( ui_Probe1Name, 24 );
lv_obj_set_y( ui_Probe1Name, 17 );
lv_obj_set_align( ui_Probe1Name, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_Probe1Name,"Probe 1");
lv_obj_set_style_text_color(ui_Probe1Name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Probe1Name, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Probe2Group = lv_obj_create(ui_ProbeGroup);
lv_obj_set_width( ui_Probe2Group, 90);
lv_obj_set_height( ui_Probe2Group, 422);
lv_obj_set_align( ui_Probe2Group, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_Probe2Group, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Probe2Group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Probe2Group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Probe2Group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Probe2Group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Probe2Temp = lv_bar_create(ui_Probe2Group);
lv_bar_set_range(ui_Probe2Temp, 32,230);
lv_bar_set_value(ui_Probe2Temp,84,LV_ANIM_OFF);
lv_obj_set_width( ui_Probe2Temp, 10);
lv_obj_set_height( ui_Probe2Temp, 375);
lv_obj_set_x( ui_Probe2Temp, 15 );
lv_obj_set_y( ui_Probe2Temp, 0 );
lv_obj_set_align( ui_Probe2Temp, LV_ALIGN_TOP_MID );
lv_obj_set_style_bg_color(ui_Probe2Temp, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Probe2Temp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Probe2Temp, lv_color_hex(0xFF0D0D), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Probe2Temp, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Probe2Temp, lv_color_hex(0xFFCD0B), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_Probe2Temp, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Probe2Temp, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Probe2Temp, LV_GRAD_DIR_VER, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Probe2Target = lv_slider_create(ui_Probe2Group);
lv_slider_set_range(ui_Probe2Target, 32,230);
lv_slider_set_value( ui_Probe2Target, 230, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_Probe2Target)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_Probe2Target, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Probe2Target, 16);
lv_obj_set_height( ui_Probe2Target, 382);
lv_obj_set_x( ui_Probe2Target, 15 );
lv_obj_set_y( ui_Probe2Target, -1 );
lv_obj_set_align( ui_Probe2Target, LV_ALIGN_TOP_MID );
lv_obj_set_style_bg_color(ui_Probe2Target, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Probe2Target, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Probe2Target, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Probe2Target, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Probe2Target, 30, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Probe2Target, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Probe2Target, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Probe2TempLabel = lv_label_create(ui_Probe2Group);
lv_obj_set_width( ui_Probe2TempLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Probe2TempLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Probe2TempLabel, -15 );
lv_obj_set_y( ui_Probe2TempLabel, 150 );
lv_label_set_text(ui_Probe2TempLabel,"84°");
lv_obj_set_style_text_color(ui_Probe2TempLabel, lv_color_hex(0xAB72C1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Probe2TempLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Probe2TempLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Probe2TargetLabel = lv_label_create(ui_Probe2Group);
lv_obj_set_width( ui_Probe2TargetLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Probe2TargetLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Probe2TargetLabel, -15 );
lv_obj_set_y( ui_Probe2TargetLabel, 0 );
lv_label_set_text(ui_Probe2TargetLabel,"185°");
lv_obj_set_style_text_font(ui_Probe2TargetLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Probe2Name = lv_label_create(ui_Probe2Group);
lv_obj_set_width( ui_Probe2Name, 57);
lv_obj_set_height( ui_Probe2Name, 19);
lv_obj_set_x( ui_Probe2Name, 17 );
lv_obj_set_y( ui_Probe2Name, 21 );
lv_obj_set_align( ui_Probe2Name, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_Probe2Name,"Probe 2");
lv_obj_set_style_text_color(ui_Probe2Name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Probe2Name, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Probe3Group = lv_obj_create(ui_ProbeGroup);
lv_obj_set_width( ui_Probe3Group, 90);
lv_obj_set_height( ui_Probe3Group, 421);
lv_obj_set_align( ui_Probe3Group, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_Probe3Group, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Probe3Group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Probe3Group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Probe3Group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Probe3Group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Probe3Temp = lv_bar_create(ui_Probe3Group);
lv_bar_set_range(ui_Probe3Temp, 32,230);
lv_bar_set_value(ui_Probe3Temp,84,LV_ANIM_OFF);
lv_obj_set_width( ui_Probe3Temp, 10);
lv_obj_set_height( ui_Probe3Temp, 375);
lv_obj_set_x( ui_Probe3Temp, 15 );
lv_obj_set_y( ui_Probe3Temp, 0 );
lv_obj_set_align( ui_Probe3Temp, LV_ALIGN_TOP_MID );
lv_obj_set_style_bg_color(ui_Probe3Temp, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Probe3Temp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Probe3Temp, lv_color_hex(0xFF0D0D), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Probe3Temp, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Probe3Temp, lv_color_hex(0xFFCD0B), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_Probe3Temp, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Probe3Temp, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Probe3Temp, LV_GRAD_DIR_VER, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Probe3Target = lv_slider_create(ui_Probe3Group);
lv_slider_set_range(ui_Probe3Target, 32,230);
lv_slider_set_value( ui_Probe3Target, 230, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_Probe3Target)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_Probe3Target, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Probe3Target, 16);
lv_obj_set_height( ui_Probe3Target, 382);
lv_obj_set_x( ui_Probe3Target, 15 );
lv_obj_set_y( ui_Probe3Target, -1 );
lv_obj_set_align( ui_Probe3Target, LV_ALIGN_TOP_MID );
lv_obj_set_style_bg_color(ui_Probe3Target, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Probe3Target, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Probe3Target, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Probe3Target, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Probe3Target, 30, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Probe3Target, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Probe3Target, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Probe3TempLabel = lv_label_create(ui_Probe3Group);
lv_obj_set_width( ui_Probe3TempLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Probe3TempLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Probe3TempLabel, -15 );
lv_obj_set_y( ui_Probe3TempLabel, 150 );
lv_label_set_text(ui_Probe3TempLabel,"84°");
lv_obj_set_style_text_color(ui_Probe3TempLabel, lv_color_hex(0xAB72C1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Probe3TempLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Probe3TempLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Probe3TargetLabel = lv_label_create(ui_Probe3Group);
lv_obj_set_width( ui_Probe3TargetLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Probe3TargetLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Probe3TargetLabel, -15 );
lv_obj_set_y( ui_Probe3TargetLabel, 0 );
lv_label_set_text(ui_Probe3TargetLabel,"185°");
lv_obj_set_style_text_font(ui_Probe3TargetLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Probe3Name = lv_label_create(ui_Probe3Group);
lv_obj_set_width( ui_Probe3Name, 58);
lv_obj_set_height( ui_Probe3Name, 18);
lv_obj_set_x( ui_Probe3Name, 19 );
lv_obj_set_y( ui_Probe3Name, 20 );
lv_obj_set_align( ui_Probe3Name, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_Probe3Name,"Probe 3");
lv_obj_set_style_text_color(ui_Probe3Name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Probe3Name, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GrillPanel = lv_obj_create(ui_DashboardPanel);
lv_obj_set_width( ui_GrillPanel, 243);
lv_obj_set_height( ui_GrillPanel, 233);
lv_obj_set_x( ui_GrillPanel, -82 );
lv_obj_set_y( ui_GrillPanel, 3 );
lv_obj_set_align( ui_GrillPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_GrillPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_GrillPanel, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_GrillPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_GrillPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_GrillPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GrillTemp = lv_arc_create(ui_GrillPanel);
lv_obj_set_width( ui_GrillTemp, lv_pct(108));
lv_obj_set_height( ui_GrillTemp, lv_pct(109));
lv_obj_set_align( ui_GrillTemp, LV_ALIGN_CENTER );
lv_arc_set_range(ui_GrillTemp, 32,752);
lv_obj_set_style_bg_img_tiled(ui_GrillTemp, false, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_GrillTemp, lv_color_hex(0x55042B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_GrillTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_GrillTemp, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_GrillTemp, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_GrillTemp, 15, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_GrillTemp, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_GrillTemp, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_GrillTempLabel = lv_label_create(ui_GrillTemp);
lv_obj_set_width( ui_GrillTempLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_GrillTempLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_GrillTempLabel, 0 );
lv_obj_set_y( ui_GrillTempLabel, -15 );
lv_obj_set_align( ui_GrillTempLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_GrillTempLabel,"385°");
lv_obj_set_style_text_color(ui_GrillTempLabel, lv_color_hex(0xAB72C1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_GrillTempLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_GrillTempLabel, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GrillTargetLabel = lv_label_create(ui_GrillTemp);
lv_obj_set_width( ui_GrillTargetLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_GrillTargetLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_GrillTargetLabel, 0 );
lv_obj_set_y( ui_GrillTargetLabel, 30 );
lv_obj_set_align( ui_GrillTargetLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_GrillTargetLabel,"475");
lv_obj_set_style_text_font(ui_GrillTargetLabel, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_NavMenu = lv_obj_create(ui_DashboardPanel);
lv_obj_set_width( ui_NavMenu, 74);
lv_obj_set_height( ui_NavMenu, 348);
lv_obj_set_x( ui_NavMenu, -25 );
lv_obj_set_y( ui_NavMenu, -2 );
lv_obj_set_align( ui_NavMenu, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( ui_NavMenu, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Smokeplus = lv_obj_create(ui_DashboardPanel);
lv_obj_set_width( ui_Smokeplus, 108);
lv_obj_set_height( ui_Smokeplus, 84);
lv_obj_set_align( ui_Smokeplus, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_Smokeplus,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Smokeplus, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_BETWEEN);
lv_obj_clear_flag( ui_Smokeplus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SmokeplusLabel = lv_label_create(ui_Smokeplus);
lv_obj_set_width( ui_SmokeplusLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SmokeplusLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SmokeplusLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SmokeplusLabel,"Smoke Plus");

ui_SmokePlusSwitch = lv_switch_create(ui_Smokeplus);
lv_obj_set_width( ui_SmokePlusSwitch, 63);
lv_obj_set_height( ui_SmokePlusSwitch, 36);
lv_obj_set_x( ui_SmokePlusSwitch, 34 );
lv_obj_set_y( ui_SmokePlusSwitch, -4 );
lv_obj_set_align( ui_SmokePlusSwitch, LV_ALIGN_CENTER );

lv_obj_set_style_bg_color(ui_SmokePlusSwitch, lv_color_hex(0x6F75E9), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_SmokePlusSwitch, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

ui_Mode = lv_obj_create(ui_DashboardPanel);
lv_obj_set_width( ui_Mode, 170);
lv_obj_set_height( ui_Mode, 84);
lv_obj_set_x( ui_Mode, -189 );
lv_obj_set_y( ui_Mode, 0 );
lv_obj_set_align( ui_Mode, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_Mode,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Mode, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_BETWEEN);
lv_obj_clear_flag( ui_Mode, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ModeLabel = lv_label_create(ui_Mode);
lv_obj_set_width( ui_ModeLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ModeLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ModeLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_ModeLabel,"Mode");

ui_ModeList = lv_dropdown_create(ui_Mode);
lv_dropdown_set_options( ui_ModeList, "Smoke\nOption 2\nOption 3" );
lv_obj_set_width( ui_ModeList, 150);
lv_obj_set_height( ui_ModeList, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ModeList, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ModeList, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_Pellets = lv_obj_create(ui_DashboardPanel);
lv_obj_set_width( ui_Pellets, 135);
lv_obj_set_height( ui_Pellets, 90);
lv_obj_set_x( ui_Pellets, -209 );
lv_obj_set_y( ui_Pellets, 349 );
lv_obj_set_align( ui_Pellets, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_Pellets,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Pellets, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_BETWEEN);
lv_obj_clear_flag( ui_Pellets, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PelletsLabel = lv_label_create(ui_Pellets);
lv_obj_set_width( ui_PelletsLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PelletsLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PelletsLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_PelletsLabel,"Pellets");

ui_Label1 = lv_label_create(ui_Pellets);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"80%");
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image2 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image2, &ui_img_flame_png);
lv_obj_set_width( ui_Image2, 73);
lv_obj_set_height( ui_Image2, 103);
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image2,200);

lv_obj_add_event_cb(ui_Probe1Target, ui_event_Probe1Target, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Probe2Target, ui_event_Probe2Target, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Probe3Target, ui_event_Probe3Target, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_GrillTemp, ui_event_GrillTemp, LV_EVENT_ALL, NULL);

}

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
