// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.2
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_events.h"
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_DashboardPanel;
extern lv_obj_t *ui_ProbeGroup;
extern lv_obj_t *ui_Probe1Group;
extern lv_obj_t *ui_Probe1Temp;
void ui_event_Probe1Target( lv_event_t * e);
extern lv_obj_t *ui_Probe1Target;
extern lv_obj_t *ui_Probe1TempLabel;
extern lv_obj_t *ui_Probe1TargetLabel;
extern lv_obj_t *ui_Probe1Name;
extern lv_obj_t *ui_Probe2Group;
extern lv_obj_t *ui_Probe2Temp;
void ui_event_Probe2Target( lv_event_t * e);
extern lv_obj_t *ui_Probe2Target;
extern lv_obj_t *ui_Probe2TempLabel;
extern lv_obj_t *ui_Probe2TargetLabel;
extern lv_obj_t *ui_Probe2Name;
extern lv_obj_t *ui_Probe3Group;
extern lv_obj_t *ui_Probe3Temp;
void ui_event_Probe3Target( lv_event_t * e);
extern lv_obj_t *ui_Probe3Target;
extern lv_obj_t *ui_Probe3TempLabel;
extern lv_obj_t *ui_Probe3TargetLabel;
extern lv_obj_t *ui_Probe3Name;
extern lv_obj_t *ui_GrillPanel;
void ui_event_GrillTemp( lv_event_t * e);
extern lv_obj_t *ui_GrillTemp;
extern lv_obj_t *ui_GrillTempLabel;
extern lv_obj_t *ui_GrillTargetLabel;
extern lv_obj_t *ui_NavMenu;
extern lv_obj_t *ui_Smokeplus;
extern lv_obj_t *ui_SmokeplusLabel;
extern lv_obj_t *ui_SmokePlusSwitch;
extern lv_obj_t *ui_Mode;
extern lv_obj_t *ui_ModeLabel;
extern lv_obj_t *ui_ModeList;
extern lv_obj_t *ui_Pellets;
extern lv_obj_t *ui_PelletsLabel;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui____initial_actions0;


LV_IMG_DECLARE( ui_img_flame_png);   // assets/flame.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
