// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.2
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_events.h"
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_DashboardPanel;
extern lv_obj_t *ui_ProbeGroup;
extern lv_obj_t *ui_Probe1Group;
extern lv_obj_t *ui_Probe1Temp;
void ui_event_Probe1Target( lv_event_t * e);
extern lv_obj_t *ui_Probe1Target;
extern lv_obj_t *ui_Probe1TempLabel;
extern lv_obj_t *ui_Probe1TargetLabel;
extern lv_obj_t *ui_Probe1Name;
extern lv_obj_t *ui_Probe2Group;
extern lv_obj_t *ui_Probe2Temp;
void ui_event_Probe2Target( lv_event_t * e);
extern lv_obj_t *ui_Probe2Target;
extern lv_obj_t *ui_Probe2TempLabel;
extern lv_obj_t *ui_Probe2TargetLabel;
extern lv_obj_t *ui_Probe2Name;
extern lv_obj_t *ui_Probe3Group;
extern lv_obj_t *ui_Probe3Temp;
void ui_event_Probe3Target( lv_event_t * e);
extern lv_obj_t *ui_Probe3Target;
extern lv_obj_t *ui_Probe3TempLabel;
extern lv_obj_t *ui_Probe3TargetLabel;
extern lv_obj_t *ui_Probe3Name;
extern lv_obj_t *ui_GrillPanel;
void ui_event_GrillTemp( lv_event_t * e);
extern lv_obj_t *ui_GrillTemp;
extern lv_obj_t *ui_GrillTempLabel;
extern lv_obj_t *ui_GrillTargetLabel;
extern lv_obj_t *ui_Smokeplus;
extern lv_obj_t *ui_SmokeplusLabel;
extern lv_obj_t *ui_SmokePlusSwitch;
extern lv_obj_t *ui_Mode;
extern lv_obj_t *ui_ModeLabel;
extern lv_obj_t *ui_ModeList;
extern lv_obj_t *ui_Pellets;
extern lv_obj_t *ui_PelletsLabel;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_HistoryPanel;
extern lv_obj_t *ui_NavMenu;
void ui_event_MainImg( lv_event_t * e);
extern lv_obj_t *ui_MainImg;
void ui_event_HistoryImg( lv_event_t * e);
extern lv_obj_t *ui_HistoryImg;
extern lv_obj_t *ui_ReceipeImg;
extern lv_obj_t *ui_PelletImg;
extern lv_obj_t *ui_EventsImg;
extern lv_obj_t *ui_SettingsImg;
extern lv_obj_t *ui_LogoImg;
extern lv_obj_t *ui_StatusPanel;
extern lv_obj_t *ui_TimeLabel;
extern lv_obj_t *ui_FanImg;
extern lv_obj_t *ui_IgnitionImg;
extern lv_obj_t *ui_MotorImg;
extern lv_obj_t *ui____initial_actions0;


LV_IMG_DECLARE( ui_img_ic_grill_png);   // assets/ic_grill.png
LV_IMG_DECLARE( ui_img_ic_menu_history_png);   // assets/ic_menu_history.png
LV_IMG_DECLARE( ui_img_ic_menu_recipes_png);   // assets/ic_menu_recipes.png
LV_IMG_DECLARE( ui_img_ic_grill_pellets_png);   // assets/ic_grill_pellets.png
LV_IMG_DECLARE( ui_img_ic_menu_events_png);   // assets/ic_menu_events.png
LV_IMG_DECLARE( ui_img_ic_menu_settings_png);   // assets/ic_menu_settings.png
LV_IMG_DECLARE( ui_img_flame_png);   // assets/flame.png
LV_IMG_DECLARE( ui_img_ic_settings_pwm_png);   // assets/ic_settings_pwm.png
LV_IMG_DECLARE( ui_img_ic_ignition_png);   // assets/ic_ignition.png
LV_IMG_DECLARE( ui_img_667599197);   // assets/ic_electric-motor.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
